final/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'final.views.home', name='home'),
    url(r'^shop/', include('shop.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

shop/urls.py
from django.conf.urls import patterns, url

from shop import views
urlpatterns= patterns('',
url(r'^$', views.product, name='product')
)

shop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=30)
    sup_cat = models.ForeignKey("self", blank=True,null=True)
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=30)
    creator = models.CharField(max_length=30)
    publisher = models.CharField(max_length=30)
    category = models.ForeignKey(Category)
    price = models.DecimalField(max_digits=6,decimal_places=2)
    number = models.DecimalField(max_digits=6,decimal_places=0)
    small_image = models.FilePathField(path='./shop/static/images/tmb', null=True, blank=True)
    large_image = models.FilePathField(path='./shop/static/images/lg', null=True, blank=True)
    availability = models.BooleanField()
    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render
from shop.models import Product, Category


def product(request):
    prod = Product.objects.filter(id=2)[0]
    cats = Category.objects.all()
    context = {'product': prod, 'categories': cats}
    return render(request, 'product.html', context)

shop/templates/base.html
<!DOCTYPE html >
<html lang="en" dir="rtl">
<head>
  <meta charset="utf-8">

  <title>صفحه اصلی</title>

  <!-- Bootstrap core CSS -->
  <!--<link href='http://awebfont.ir/css?id=1554&mode=wl' rel='stylesheet' type='text/css'>-->
  
  <link href="{{ STATIC_URL }}css/bootstrap.css" rel="stylesheet">
  <link href="{{ STATIC_URL }}css/base.css" rel="stylesheet">
  <link href="{{ STATIC_URL }}font-awesome-4.0.3/css/font-awesome.css" rel="stylesheet">
   {% block extra_css  %}
   {% endblock %}

  <script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
  <script src="{{ STATIC_URL }}js/bootstrap.js"></script>
  <script src="{{ STATIC_URL }}js/bootstrap-hover-dropdown.js"></script>
   {% block extra_js  %}
   {% endblock %}

</head>

<body>
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="navbar-collapse collapse" id="navbar-main">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#"><i class="fa fa-home"></i></a></li>
          <li><a data-hover="dropdown" href="#cart"><i class="fa fa-shopping-cart"></i> سبد خرید  </a>
            <ul class="dropdown-menu">
              <li><a href="#dropdown1">کوفت</a></li>
              <li><a href="#dropdown2">درد</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-left">
          <li><a href="#"><i class="fa fa-cogs fa-lg"></i></a></li>
          <!--  <li><a href="#"><i class="fa fa-search fa-lg"></i></a></li>-->
        </ul>
        <form class="navbar-form navbar-left">
          <input style="height:36px; margin-top:4px;" type="text" class="form-control col-lg-8" placeholder="جستجو...">
        </form>
        
      </div>
    </div>
  </div>

  <div class="container main-container">

      <div class="row">
        <div class=col-lg-12>

          <ul class="nav nav-pills nav-justified cat-nav">
            {% for cat in categories %}
                {% ifequal cat.sup_cat null %}
                    <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-angle-left"></i> {{ cat.name }}</a>
                        <ul class="dropdown-menu cat-list">
                            <ul class="nav nav-pills">
                                {% for sub_cat in cat.category_set.all%}
                                    <li class="sub-cat"><a href="#">{{ sub_cat.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </ul>
                    </li>
                {% endifequal %}
            {% endfor %}
          {% comment %}
            <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-heart"></i> برترین ها</a>
              <ul class="dropdown-menu cat-list">
                <ul class="nav nav-pills">
                  <li class="sub-cat"><a href="#">کوفت</a></li>
                </ul>
              </ul>
            </li>
            <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-book"></i> کتاب</a>
              <ul class="dropdown-menu cat-list">
                <ul class="nav nav-pills">
                  <li class="sub-cat"><a href="#">زهرمار</a></li>
                </ul>
              </ul>
            </li>
            <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-music"></i> موسیقی</a></a>
              <ul class="dropdown-menu cat-list">
                <ul class="nav nav-pills">
                  <li class="sub-cat"><a href="#">مرض</a></li>
                </ul>
              </ul>
            </li>
            <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-film"></i> فیلم</a>
              <ul class="dropdown-menu cat-list">
                <ul class="nav nav-pills">
                  <li class="sub-cat"><a href="#">درد</a></li>
                </ul>
              </ul>
            </li>
            <li style="position: inherit"><a data-hover="dropdown" data-toggle="tab"><i class="fa fa-desktop"></i> سریال</a></a>
              <ul class="dropdown-menu cat-list">
                <ul class="nav nav-pills">
                  <li class="sub-cat"><a href="#">ساکت</a></li>
                </ul>
              </ul>
            </li>
            {% endcomment %}
            
          </ul>
        </div>
      </div>
    </div>
    <div class="container sub-container"> <!--uncommon parts!-->
        {% block content %}
        {% endblock%}
    </div>
  </body>
  </html>

shop/templates/product.html
{% extends "base.html" %}
{% block extra_css  %}
    <link href="{{ STATIC_URL }}css/prod.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="row">
      <div class="col-lg-7 col-lg-offset-1" style="padding: 0px">
        <div class="panel panel-primary prod-detail">
          <div class="panel-body">

            <div class="well">
              <h1>{{ product.name}}</h1>
            </div>

            <table class="table">
              <tbody>
                <tr>
                  <td>پدیدآورنده: </td>
                  <td>{{ product.creator }}</td>
                </tr>
                <tr>
                  <td>وضعیت: </td>
                  <td>
                      {% if product.availability %}
                           موجود
                      {% else %}
                            تمام شده
                      {% endif %}
                  </td>
                </tr>
                <tr>
                  <td>عرضه کننده:</td>
                  <td>{{ product.publisher }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-3"style="padding: 0px">
        <div class="panel panel-primary prod-thumb">
          <div class="panel-body">
            <img class="prod-img" src={{ product.small_image }}>
            <div class="well well-sm prod-price">
                <span>قیمت: </span><span>{{ product.price }}</span><span> تومان</span>
            </div>
            <button type="button" class="btn btn-primary btn-block"><i class="fa fa-shopping-cart"></i> اضافه به سبد خرید </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-10 col-lg-offset-1" id="comments-col">
        <button type="button" class="btn btn-primary" data-toggle="collapse" href="#comments">
          <i class="fa fa-angle-double-down"></i> نظرات کاربران
        </button>
        <div class="panel panel-default">
          <div id="comments" class="panel-collapse collapse">
            <div id="commentsList" class="panel-body">
              <div class='panel panel-default'>
                <div class='panel-body'>
                  <form role="form">
                    <div class="form-group">
                      <label for="nameInput">نام: </label>
                      <input id="nameInput" type="text" class="form-control input-sm">
                      <label for="commentInput">متن نظر: </label>
                      <textarea id ="commentInput" class="form-control input-sm" rows="3"></textarea>
                    </div>
                    <button type="button" onclick="addNewComment()" class="btn btn-primary btn-sm pull-left">بفرســـــت</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock%}